// Uses Declarative syntax to run commands inside a container.
pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
template:
  metadata:
    labels:
      app: react-app
  spec:
    containers:
    - name: my-react-app
      image: yesinaleksey/reactapp:v1
---
apiVersion: v1
kind: Service
metadata:
  name: my-react-app-svc
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - name: my-app
      port: 3000
      targetPort: 3000
'''
            defaultContainer 'shell'
        }
    }
    stages {
        stage('Main') {
            steps {
                sh 'sleep 100'
            }
        }
    }
}
