pipeline {
    agent none

    stages {
        stage("Deploy Pod") {
          agent {
            kubernetes {
                    yaml '''
apiVersion: v1
kind: Pod
metadata:
  name: podjs
spec:
  containers:
  - name: reactjs
    image: yesinaleksey/k8s-react:v1
    ports:
    - containerPort: 80
    
'''
    }
  }
            stages {
               stage("build") {
                   steps {
                       sh "hostname"
                   }
               }

            }
            
        stage("Deploy Service") {
          agent {
            kubernetes {
                    yaml '''
apiVersion: v1
kind: Service
metadata:
  name: react
spec:
  type: NodePort
  selector:
    project: podjs
  ports:
    - name: app-listener
      protocol: TCP
      port: 80
      targetPort: 80
'''
    }
  }
            stages {
               stage("build") {
                   steps {
                       sh "hostname"
                       sh "sleep 150"
                   }
               }

            } 
            
        }
   }
}
}
