pipeline {
    agent none

    stages {
      stage("Deploy Pod") {
        agent {
          kubernetes {
                  yaml '''
apiVersion: v1
kind: Pod
metadata:
  name: podjs
spec:
  containers:
  - name: reactjs
    image: yesinaleksey/k8s-react:v1
    ports:
    - containerPort: 80
'''
    }
  }
            stages {
              stage("build") {
                steps {
                  sh "hostname"
                }
              }
            }
            stages {
              stage("build2") {
                steps {
                  sh "hostname"
                  sh "sleep 150"
                }
              }
            } 
        }
    }
}
