pipeline {
  agent {
    kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: shell
    image: ubuntu
    command:
    - sleep
    args:
    - infinity
'''
    }
  }
   
    stages {
        stage('Deploy Service') {
          agent {
            kubernetes {
                    yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: shell
    image: yesinaleksey/k8s-react:v1
    command:
    - sleep
    args:
    - infinity
'''
            }
          }
        }
        
          stages('Finish Stage') {
            stage('hostname')
              steps {
                echo "============FINISHING SLEEP==================="
                sh 'hostname'
                sh 'sleep 200'
              }
            }        
          }
    }
}
