pipeline {
    agent none

    stages {
        stage("build and test the project") {
          agent {
            kubernetes {
                    yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: shell
    image: ubuntu
    command:
    - sleep
    args:
    - infinity
'''
    }
  }
            stages {
               stage("build") {
                   steps {
                       sh "hostname"
                   }
               }
               stage("test") {
                   steps {
                       sh "./test.sh"
                   }
               }
            }
            post {
                success {
                    stash name: "artifacts", includes: "artifacts/**/*"
                }
            }
        }
}
