pipeline {
    agent none
    stages {
        stage('deploy pod') {
            agent {
              kubernetes {
                    yaml '''
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
'''
    }
  }
            steps {
                sh 'hostname'
            }
        }
        stage('deploy service') {
            agent {
              kubernetes {
                cloud 'kubernetes'
                namespace 'jenkins'
              }
            }

            steps {
              sh 'curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.20.5/bin/linux/amd64/kubectl"'  
              sh 'chmod u+x ./kubectl'  
              sh './kubectl get pods'            
            }
        }
    }
}
