apiVersion: v1
kind: Pod
metadata:
  name: react
spec:
  containers:
  - name: reactjs
    image: yesinaleksey/k8s-react:v1
---
apiVersion: v1
kind: Service
metadata:
  name: my-js-service
spec:
  selector:
    project: react
  ports:
    - name: app-listener
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
