apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app-dep
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 1
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name : react-app
          image: yesinaleksey/reactapp:v1
